[workspace]
publish = false
release = false
git_release_enable = false
changelog_config = "cliff.toml"
changelog_update = true
git_tag_enable = true

[[package]]
name = "edc-connector-client"
changelog_path = "edc-connector-client/CHANGELOG.md"
publish = true
release = true
git_release_enable = true
changelog_update = true

[[package]]
name = "edc-connector-tui"
changelog_path = "edc-connector-tui/CHANGELOG.md"
publish = true
changelog_update = true
