//! Cached documents: JSON-LD contexts and JSON schemas the connector serves
//! from its own cache instead of fetching them remotely.

use bon::Builder;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DocumentType {
    JsonLd,
    JsonSchema,
    #[serde(untagged)]
    Other(String),
}

/// When the connector fetches the document from its `url`.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PullStrategy {
    Never,
    IfNotPresent,
    Always,
    #[serde(untagged)]
    Other(String),
}

/// A stored cached document (`@type: CachedDocument`).
#[derive(Debug, Serialize, Deserialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct CachedDocument {
    #[builder(into)]
    #[serde(rename = "@id")]
    id: String,
    #[builder(default = "CachedDocument".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    #[builder(into)]
    url: String,
    #[builder(default = DocumentType::JsonLd)]
    #[serde(default = "default_document_type")]
    document_type: DocumentType,
    #[builder(default = PullStrategy::Never)]
    #[serde(default = "default_pull_strategy")]
    pull_strategy: PullStrategy,
    /// The document itself, an arbitrary JSON tree.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    content: Option<Value>,
    #[builder(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    updated_at: Option<i64>,
}

fn default_document_type() -> DocumentType {
    DocumentType::JsonLd
}

fn default_pull_strategy() -> PullStrategy {
    PullStrategy::Never
}

impl CachedDocument {
    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn url(&self) -> &str {
        &self.url
    }

    pub fn document_type(&self) -> &DocumentType {
        &self.document_type
    }

    pub fn pull_strategy(&self) -> &PullStrategy {
        &self.pull_strategy
    }

    pub fn content(&self) -> Option<&Value> {
        self.content.as_ref()
    }

    pub fn updated_at(&self) -> Option<i64> {
        self.updated_at
    }
}

/// A cached document to create; the id is generated by the connector when omitted.
#[derive(Debug, Serialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct NewCachedDocument {
    #[builder(into)]
    #[serde(rename = "@id", skip_serializing_if = "Option::is_none")]
    id: Option<String>,
    #[builder(default = "CachedDocument".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    #[builder(into)]
    url: String,
    #[builder(default = DocumentType::JsonLd)]
    document_type: DocumentType,
    #[builder(default = PullStrategy::Never)]
    pull_strategy: PullStrategy,
    #[serde(skip_serializing_if = "Option::is_none")]
    content: Option<Value>,
}

impl NewCachedDocument {
    pub fn id(&self) -> Option<&str> {
        self.id.as_deref()
    }

    pub fn url(&self) -> &str {
        &self.url
    }

    pub fn content(&self) -> Option<&Value> {
        self.content.as_ref()
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use serde_json::json;

    use super::{CachedDocument, DocumentType, NewCachedDocument, PullStrategy};

    #[test]
    fn should_serialize_a_new_document() {
        let document = NewCachedDocument::builder()
            .url("https://example.com/schema.json")
            .document_type(DocumentType::JsonSchema)
            .content(json!({"type": "object"}))
            .build();

        assert_eq!(
            serde_json::to_value(&document).unwrap(),
            json!({
                "@type": "CachedDocument",
                "url": "https://example.com/schema.json",
                "documentType": "JSON_SCHEMA",
                "pullStrategy": "NEVER",
                "content": {"type": "object"}
            })
        );
    }

    #[test]
    fn should_deserialize_array_content_and_missing_timestamp() {
        let document: CachedDocument = serde_json::from_value(json!({
            "@id": "1",
            "@type": "CachedDocument",
            "url": "https://example.com/context.jsonld",
            "documentType": "JSON_LD",
            "pullStrategy": "IF_NOT_PRESENT",
            "content": ["https://a", {"@vocab": "https://b/"}]
        }))
        .unwrap();

        assert_eq!(document.pull_strategy(), &PullStrategy::IfNotPresent);
        assert!(document.content().unwrap().is_array());
        assert_eq!(document.updated_at(), None);
    }
}
