//! DCP (Decentralized Claims Protocol) scopes: the credential scopes a
//! participant requests from a counter party for a profile.

use bon::Builder;
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DcpScopeType {
    /// Always requested.
    Default,
    /// Requested when a policy references it.
    Policy,
    #[serde(untagged)]
    Other(String),
}

/// A stored DCP scope (`@type: DcpScope`).
#[derive(Debug, Serialize, Deserialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct DcpScope {
    #[builder(into)]
    #[serde(rename = "@id")]
    id: String,
    #[builder(default = "DcpScope".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    #[builder(default = DcpScopeType::Default)]
    #[serde(rename = "type", default = "default_scope_type")]
    kind: DcpScopeType,
    /// The scope string, e.g. `org.eclipse.edc.vc.type:MembershipCredential:read`.
    #[builder(into)]
    value: String,
    /// The dataspace profile the scope applies to.
    #[builder(into)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    profile: Option<String>,
    #[builder(into)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    prefix_mapping: Option<String>,
}

fn default_scope_type() -> DcpScopeType {
    DcpScopeType::Default
}

impl DcpScope {
    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn kind(&self) -> &DcpScopeType {
        &self.kind
    }

    pub fn value(&self) -> &str {
        &self.value
    }

    pub fn profile(&self) -> Option<&str> {
        self.profile.as_deref()
    }

    pub fn prefix_mapping(&self) -> Option<&str> {
        self.prefix_mapping.as_deref()
    }
}

/// A DCP scope to create; the id is generated by the connector when omitted.
#[derive(Debug, Serialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct NewDcpScope {
    #[builder(into)]
    #[serde(rename = "@id", skip_serializing_if = "Option::is_none")]
    id: Option<String>,
    #[builder(default = "DcpScope".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    #[builder(default = DcpScopeType::Default)]
    #[serde(rename = "type")]
    kind: DcpScopeType,
    #[builder(into)]
    value: String,
    #[builder(into)]
    #[serde(skip_serializing_if = "Option::is_none")]
    profile: Option<String>,
    #[builder(into)]
    #[serde(skip_serializing_if = "Option::is_none")]
    prefix_mapping: Option<String>,
}

impl NewDcpScope {
    pub fn id(&self) -> Option<&str> {
        self.id.as_deref()
    }

    pub fn kind(&self) -> &DcpScopeType {
        &self.kind
    }

    pub fn value(&self) -> &str {
        &self.value
    }

    pub fn profile(&self) -> Option<&str> {
        self.profile.as_deref()
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use serde_json::json;

    use super::{DcpScope, DcpScopeType, NewDcpScope};

    #[test]
    fn should_serialize_a_new_scope() {
        let scope = NewDcpScope::builder()
            .kind(DcpScopeType::Policy)
            .value("scope-value")
            .profile("dsp2025_1")
            .build();

        assert_eq!(
            serde_json::to_value(&scope).unwrap(),
            json!({
                "@type": "DcpScope",
                "type": "POLICY",
                "value": "scope-value",
                "profile": "dsp2025_1"
            })
        );
    }

    #[test]
    fn should_deserialize_an_unknown_type() {
        let scope: DcpScope = serde_json::from_value(json!({
            "@id": "1", "@type": "DcpScope", "type": "FUTURE", "value": "v"
        }))
        .unwrap();

        assert_eq!(scope.kind(), &DcpScopeType::Other("FUTURE".to_string()));
        assert_eq!(scope.profile(), None);
    }
}
