//! Schema validator registrations: JSON schemas the management API validates
//! request bodies of a given `@type` against.

use bon::Builder;
use serde::{Deserialize, Serialize};
use serde_with::{formats::PreferMany, serde_as, OneOrMany};

/// A stored registration (`@type: SchemaValidatorRegistration`).
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct SchemaValidatorRegistration {
    #[builder(field)]
    #[serde(default)]
    #[serde_as(deserialize_as = "OneOrMany<_, PreferMany>")]
    profiles: Vec<String>,
    #[builder(into)]
    #[serde(rename = "@id")]
    id: String,
    #[builder(default = "SchemaValidatorRegistration".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    /// Management API version the schema applies to, e.g. `v5`.
    #[builder(into)]
    version: String,
    /// The JSON-LD `@type` of the bodies to validate.
    #[builder(into)]
    validated_type: String,
    /// URL of the JSON schema.
    #[builder(into)]
    schema: String,
    #[builder(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    updated_at: Option<i64>,
}

impl<S: schema_validator_registration_builder::State> SchemaValidatorRegistrationBuilder<S> {
    pub fn profile(mut self, profile: impl Into<String>) -> Self {
        self.profiles.push(profile.into());
        self
    }
}

impl SchemaValidatorRegistration {
    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn version(&self) -> &str {
        &self.version
    }

    pub fn validated_type(&self) -> &str {
        &self.validated_type
    }

    pub fn schema(&self) -> &str {
        &self.schema
    }

    pub fn profiles(&self) -> &[String] {
        &self.profiles
    }

    pub fn updated_at(&self) -> Option<i64> {
        self.updated_at
    }
}

/// A registration to create; the id is generated by the connector when omitted.
#[derive(Debug, Serialize, Clone, Builder)]
#[serde(rename_all = "camelCase")]
pub struct NewSchemaValidatorRegistration {
    #[builder(field)]
    profiles: Vec<String>,
    #[builder(into)]
    #[serde(rename = "@id", skip_serializing_if = "Option::is_none")]
    id: Option<String>,
    #[builder(default = "SchemaValidatorRegistration".to_string())]
    #[serde(rename = "@type")]
    ty: String,
    #[builder(into)]
    version: String,
    #[builder(into)]
    validated_type: String,
    #[builder(into)]
    schema: String,
}

impl<S: new_schema_validator_registration_builder::State> NewSchemaValidatorRegistrationBuilder<S> {
    pub fn profile(mut self, profile: impl Into<String>) -> Self {
        self.profiles.push(profile.into());
        self
    }
}

impl NewSchemaValidatorRegistration {
    pub fn id(&self) -> Option<&str> {
        self.id.as_deref()
    }

    pub fn validated_type(&self) -> &str {
        &self.validated_type
    }

    pub fn schema(&self) -> &str {
        &self.schema
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use serde_json::json;

    use super::{NewSchemaValidatorRegistration, SchemaValidatorRegistration};

    #[test]
    fn should_serialize_a_new_registration() {
        let registration = NewSchemaValidatorRegistration::builder()
            .version("v5")
            .validated_type("CustomType")
            .schema("https://example.com/schema.json")
            .profile("dsp2025_1")
            .build();

        assert_eq!(
            serde_json::to_value(&registration).unwrap(),
            json!({
                "@type": "SchemaValidatorRegistration",
                "version": "v5",
                "validatedType": "CustomType",
                "schema": "https://example.com/schema.json",
                "profiles": ["dsp2025_1"]
            })
        );
    }

    #[test]
    fn should_deserialize_without_profiles() {
        let registration: SchemaValidatorRegistration = serde_json::from_value(json!({
            "@id": "1",
            "@type": "SchemaValidatorRegistration",
            "version": "v5",
            "validatedType": "CustomType",
            "schema": "https://example.com/schema.json",
            "updatedAt": 42
        }))
        .unwrap();

        assert!(registration.profiles().is_empty());
        assert_eq!(registration.updated_at(), Some(42));
    }
}
